#pragma once

static const char ONBOARD_HTML[] =
"<!DOCTYPE html><html><head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>MimiClaw Admin</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f4f6f8;color:#1f2933;padding:16px;max-width:720px;margin:0 auto}"
"h1{text-align:center;margin:10px 0 4px;font-size:1.45em;color:#1557b0}"
".sub{text-align:center;color:#5f6c7b;font-size:.9em;margin-bottom:14px}"
".card{background:#fff;border:1px solid #d9e2ec;border-radius:8px;margin:12px 0;box-shadow:0 1px 2px rgba(16,24,40,.08);overflow:hidden}"
".card-hdr{display:flex;justify-content:space-between;align-items:center;padding:13px 15px;cursor:pointer;user-select:none;font-weight:650;font-size:.95em}"
".card-hdr::after{content:'\\25BC';font-size:.7em;color:#52606d;transition:transform .2s}"
".card.collapsed .card-hdr::after{transform:rotate(-90deg)}"
".card.collapsed .card-body{display:none}"
".card-body{padding:0 15px 15px}"
"label{display:block;margin:10px 0 4px;font-size:.84em;color:#52606d}"
"input,select,textarea{width:100%;padding:10px 11px;border:1px solid #bcccdc;border-radius:6px;font-size:.95em;outline:none;background:#fff;color:#1f2933}"
"textarea{min-height:120px;resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.85em;line-height:1.35}"
"input:focus,select:focus,textarea:focus{border-color:#1a73e8;box-shadow:0 0 0 2px rgba(26,115,232,.12)}"
".row{display:grid;grid-template-columns:1fr 1fr;gap:8px}"
".bar{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0}"
".btn{border:none;border-radius:6px;font-size:.94em;font-weight:650;cursor:pointer;padding:10px 12px;background:#e7eef8;color:#154b86}"
".btn.primary{background:#1a73e8;color:#fff}"
".btn.warn{background:#fdebd3;color:#8a4b0f}"
".btn.full{display:block;width:100%;margin:8px 0}"
".btn:active{opacity:.8}"
".ap-list{max-height:200px;overflow-y:auto;border:1px solid #d9e2ec;border-radius:6px;margin:8px 0}"
".ap-item{padding:10px 12px;border-bottom:1px solid #edf2f7;cursor:pointer;display:flex;justify-content:space-between;gap:8px}"
".ap-item:last-child{border-bottom:none}"
".ap-item:active{background:#edf6ff}"
".ap-rssi{color:#697586;font-size:.85em;white-space:nowrap}"
".ap-lock::before{content:'\\25CF';font-size:.65em;margin-right:5px;color:#697586}"
".out{white-space:pre-wrap;background:#101828;color:#e4e7ec;border-radius:6px;padding:10px;margin-top:8px;min-height:44px;max-height:260px;overflow:auto;font:12px/1.45 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}"
".status{text-align:center;padding:16px;color:#1557b0;font-size:1em;display:none}"
"@media(max-width:520px){body{padding:12px}.row{grid-template-columns:1fr}.btn{flex:1 1 auto}}"
"</style></head><body>"
"<h1>MimiClaw Admin</h1>"
"<p class='sub'>Local portal at 192.168.4.1</p>"

"<div class='card' id='sec-system'>"
"<div class='card-hdr' onclick='toggle(this)'>System Console</div>"
"<div class='card-body'>"
"<div class='bar'>"
"<button class='btn primary' onclick='refreshStatus()'>Refresh Status</button>"
"<button class='btn' onclick='runHeartbeat()'>Run Heartbeat</button>"
"</div>"
"<pre class='out' id='status_out'>Ready.</pre>"
"</div></div>"

"<div class='card' id='sec-wifi'>"
"<div class='card-hdr' onclick='toggle(this)'>WiFi Configuration</div>"
"<div class='card-body'>"
"<button class='btn full' onclick='scan(event)'>Scan WiFi Networks</button>"
"<div class='ap-list' id='ap-list' style='display:none'></div>"
"<label>SSID</label>"
"<input id='ssid' placeholder='WiFi network name'>"
"<label>Password</label>"
"<input id='password' type='password' placeholder='WiFi password'>"
"</div></div>"

"<div class='card collapsed' id='sec-llm'>"
"<div class='card-hdr' onclick='toggle(this)'>LLM Configuration</div>"
"<div class='card-body'>"
"<label>API Key</label>"
"<input id='api_key' type='password' placeholder='sk-...'>"
"<label>Model</label>"
"<input id='model' placeholder='claude-opus-4-5' value='claude-opus-4-5'>"
"<label>OpenAI-compatible Base URL</label>"
"<input id='base_url' placeholder='https://api.openai.com/v1 or https://third-party.example/v1'>"
"<label>Provider</label>"
"<select id='provider'>"
"<option value='anthropic'>Anthropic</option>"
"<option value='openai'>OpenAI</option>"
"</select>"
"</div></div>"

"<div class='card collapsed' id='sec-tg'>"
"<div class='card-hdr' onclick='toggle(this)'>Telegram Bot</div>"
"<div class='card-body'>"
"<label>Bot Token</label>"
"<input id='tg_token' placeholder='123456:ABC-DEF...'>"
"</div></div>"

"<div class='card collapsed' id='sec-feishu'>"
"<div class='card-hdr' onclick='toggle(this)'>Feishu</div>"
"<div class='card-body'>"
"<label>App ID</label>"
"<input id='feishu_app_id' placeholder='cli_xxxx'>"
"<label>App Secret</label>"
"<input id='feishu_app_secret' type='password' placeholder='App Secret'>"
"</div></div>"

"<div class='card collapsed' id='sec-proxy'>"
"<div class='card-hdr' onclick='toggle(this)'>Proxy</div>"
"<div class='card-body'>"
"<label>Host</label>"
"<input id='proxy_host' placeholder='192.168.1.100'>"
"<label>Port</label>"
"<input id='proxy_port' type='number' placeholder='7890'>"
"<label>Type</label>"
"<select id='proxy_type'>"
"<option value=''>None</option>"
"<option value='http'>HTTP</option>"
"<option value='socks5'>SOCKS5</option>"
"</select>"
"</div></div>"

"<div class='card collapsed' id='sec-search'>"
"<div class='card-hdr' onclick='toggle(this)'>Search</div>"
"<div class='card-body'>"
"<label>Brave Search API Key</label>"
"<input id='search_key' type='password' placeholder='BSA...'>"
"<label>Tavily API Key</label>"
"<input id='tavily_key' type='password' placeholder='tvly-...'>"
"</div></div>"

"<div class='card collapsed' id='sec-tasks'>"
"<div class='card-hdr' onclick='toggle(this)'>Task Manager</div>"
"<div class='card-body'>"
"<div class='bar'>"
"<button class='btn primary' onclick='loadTasks()'>Refresh Tasks</button>"
"</div>"
"<label>Job ID</label>"
"<div class='row'><input id='task_id' placeholder='job id'><button class='btn warn' onclick='removeTask()'>Remove Task</button></div>"
"<pre class='out' id='tasks_out'>No task data loaded.</pre>"
"</div></div>"

"<div class='card collapsed' id='sec-files'>"
"<div class='card-hdr' onclick='toggle(this)'>File Manager</div>"
"<div class='card-body'>"
"<label>List Prefix</label>"
"<div class='row'><input id='file_prefix' placeholder='/spiffs'><button class='btn' onclick='listFiles()'>List Files</button></div>"
"<label>File Path</label>"
"<input id='file_path' placeholder='/spiffs/MEMORY.md'>"
"<div class='bar'>"
"<button class='btn primary' onclick='readFile()'>Read</button>"
"<button class='btn' onclick='tailFile()'>Tail</button>"
"<button class='btn warn' onclick='appendFile()'>Append</button>"
"<button class='btn' onclick='saveFile()'>Write</button>"
"</div>"
"<textarea id='file_content' placeholder='File content'></textarea>"
"<pre class='out' id='files_out'>File tools are ready.</pre>"
"</div></div>"

"<div class='card collapsed' id='sec-memory'>"
"<div class='card-hdr' onclick='toggle(this)'>Memory Manager</div>"
"<div class='card-body'>"
"<div class='bar'><button class='btn primary' onclick='loadMemory()'>Load Memory</button><button class='btn' onclick='saveMemory()'>Save Long Term</button></div>"
"<label>Long-term Memory</label>"
"<textarea id='memory_long' placeholder='Long-term memory'></textarea>"
"<label>Memory Summary</label>"
"<textarea id='memory_summary' placeholder='On-device summary' readonly></textarea>"
"<label>Daily Note</label>"
"<textarea id='memory_note' placeholder='Append a note to today'></textarea>"
"<button class='btn full warn' onclick='appendMemory()'>Append Daily Note</button>"
"<label>Search Memory</label>"
"<div class='row'><input id='memory_query' placeholder='query'><button class='btn' onclick='searchMemory()'>Search</button></div>"
"<label>Session Cleanup</label>"
"<div class='row'><input id='cleanup_days' type='number' value='30'><button class='btn' onclick='cleanupSessions(true)'>Preview Cleanup</button></div>"
"<div class='bar'><button class='btn' onclick='summarizeMemory()'>Refresh Summary</button><button class='btn' onclick='exportMemory()'>Export Backup</button><button class='btn warn' onclick='cleanupSessions(false)'>Apply Cleanup</button></div>"
"<label>Log Tail</label>"
"<div class='row'><input id='log_path' placeholder='/spiffs/logs/mimi.log'><button class='btn' onclick='tailLog()'>Tail Log</button></div>"
"<pre class='out' id='memory_recent'>Recent daily memory not loaded.</pre>"
"</div></div>"

"<div class='card collapsed' id='sec-voice'>"
"<div class='card-hdr' onclick='toggle(this)'>Voice Hardware</div>"
"<div class='card-body'>"
"<div class='bar'><button class='btn primary' onclick='voiceStatus()'>Voice Status</button><button class='btn' onclick='voiceBeep()'>Test Beep</button></div>"
"<label>WAV Path</label>"
"<input id='voice_path' placeholder='/spiffs/voice_last.wav' value='/spiffs/voice_last.wav'>"
"<label>Record Seconds</label>"
"<div class='row'><input id='voice_seconds' type='number' value='3'><button class='btn' onclick='voiceRecord()'>Record WAV</button></div>"
"<button class='btn full' onclick='voicePlay()'>Play WAV</button>"
"<label>Streaming Server URL</label>"
"<input id='voice_stream_url' placeholder='ws://192.168.1.10:8765/mimi'>"
"<label>Streaming Codec</label>"
"<select id='voice_codec'><option value='pcm16'>PCM16</option><option value='opus'>Opus reserved</option></select>"
"<label>Stream Seconds</label>"
"<div class='row'><input id='voice_stream_seconds' type='number' value='10'><button class='btn primary' onclick='voiceStreamStart()'>Start Stream</button></div>"
"<div class='bar'><button class='btn' onclick='voiceStreamStatus()'>Stream Status</button><button class='btn warn' onclick='voiceStreamStop()'>Stop Stream</button></div>"
"<pre class='out' id='voice_out'>Voice hardware tools are ready.</pre>"
"</div></div>"

"<button class='btn primary full' onclick='saveConfig()'>Save Config &amp; Restart</button>"
"<div class='status' id='save_status'>Saving... Device will restart.</div>"

"<script>"
"function toggle(el){el.parentElement.classList.toggle('collapsed')}"
"function $(id){return document.getElementById(id)}"
"function val(id){var el=$(id);return el?el.value.trim():''}"
"function put(id,msg){$(id).textContent=typeof msg==='string'?msg:JSON.stringify(msg,null,2)}"
"function resultText(j){if(!j)return '';if(j.result!==undefined)return j.result;if(j.recent!==undefined)return 'Long-term memory loaded.\\n\\nRecent daily memory:\\n'+(j.recent||'');return JSON.stringify(j,null,2)}"
"function apiGet(url,out){put(out,'Loading...');return fetch(url).then(r=>r.json()).then(j=>{put(out,resultText(j));return j}).catch(e=>put(out,'Error: '+e))}"
"function apiPost(url,data,out){put(out,'Sending...');return fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data||{})}).then(r=>r.json()).then(j=>{put(out,resultText(j));return j}).catch(e=>put(out,'Error: '+e))}"
"function refreshStatus(){apiGet('/api/status','status_out')}"
"function runHeartbeat(){apiPost('/api/heartbeat',{},'status_out')}"
"function loadTasks(){apiGet('/api/tasks','tasks_out')}"
"function removeTask(){var id=val('task_id');if(!id){put('tasks_out','Enter a job id first.');return}apiPost('/api/task/remove',{job_id:id},'tasks_out').then(loadTasks)}"
"function listFiles(){var p=encodeURIComponent(val('file_prefix'));apiGet('/api/files'+(p?'?prefix='+p:''),'files_out')}"
"function readFile(){var p=val('file_path');if(!p){put('files_out','Enter a file path first.');return}apiGet('/api/file?path='+encodeURIComponent(p),'files_out').then(j=>{if(j&&j.result!==undefined)$('file_content').value=j.result})}"
"function tailFile(){var p=val('file_path');if(!p){put('files_out','Enter a file path first.');return}apiGet('/api/file?mode=tail&bytes=4096&path='+encodeURIComponent(p),'files_out').then(j=>{if(j&&j.result!==undefined)$('file_content').value=j.result})}"
"function saveFile(){var p=val('file_path');if(!p){put('files_out','Enter a file path first.');return}apiPost('/api/file',{path:p,content:$('file_content').value,mode:'write'},'files_out')}"
"function appendFile(){var p=val('file_path');if(!p){put('files_out','Enter a file path first.');return}apiPost('/api/file',{path:p,content:$('file_content').value,mode:'append'},'files_out')}"
"function loadMemory(){apiGet('/api/memory','memory_recent').then(j=>{if(j&&j.long_term!==undefined)$('memory_long').value=j.long_term||'';if(j&&j.summary!==undefined)$('memory_summary').value=j.summary||''})}"
"function saveMemory(){apiPost('/api/memory',{long_term:$('memory_long').value},'memory_recent')}"
"function appendMemory(){var note=$('memory_note').value.trim();if(!note){put('memory_recent','Enter a daily note first.');return}apiPost('/api/memory',{note:note},'memory_recent').then(()=>{$('memory_note').value=''})}"
"function searchMemory(){var q=val('memory_query');if(!q){put('memory_recent','Enter a query first.');return}apiPost('/api/memory',{action:'search',query:q,max_results:12},'memory_recent')}"
"function summarizeMemory(){apiPost('/api/memory',{action:'summarize',days:7,include_sessions:true},'memory_recent').then(loadMemory)}"
"function exportMemory(){apiPost('/api/memory',{action:'export',include_sessions:true,max_bytes:24576},'memory_recent')}"
"function cleanupSessions(dry){var days=parseInt(val('cleanup_days')||'30',10);apiPost('/api/memory',{action:'cleanup_sessions',older_than_days:days,dry_run:dry},'memory_recent')}"
"function tailLog(){var p=val('log_path')||'/spiffs/logs/mimi.log';apiPost('/api/memory',{action:'tail_log',path:p,max_bytes:4096},'memory_recent')}"
"function voiceStatus(){apiPost('/api/voice',{action:'status'},'voice_out')}"
"function voiceBeep(){apiPost('/api/voice',{action:'beep',freq_hz:880,duration_ms:350},'voice_out')}"
"function voiceRecord(){var p=val('voice_path')||'/spiffs/voice_last.wav';var s=parseInt(val('voice_seconds')||'3',10);apiPost('/api/voice',{action:'record',path:p,seconds:s},'voice_out')}"
"function voicePlay(){var p=val('voice_path')||'/spiffs/voice_last.wav';apiPost('/api/voice',{action:'play',path:p},'voice_out')}"
"function voiceStreamStatus(){apiPost('/api/voice',{action:'stream_status'},'voice_out')}"
"function voiceStreamConfig(){var u=val('voice_stream_url');var c=val('voice_codec')||'pcm16';return apiPost('/api/voice',{action:'stream_config',url:u,codec:c},'voice_out')}"
"function voiceStreamStart(){var s=parseInt(val('voice_stream_seconds')||'10',10);voiceStreamConfig().then(()=>apiPost('/api/voice',{action:'stream_start',seconds:s},'voice_out'))}"
"function voiceStreamStop(){apiPost('/api/voice',{action:'stream_stop'},'voice_out')}"
"function loadConfig(){fetch('/config').then(r=>r.json()).then(cfg=>{Object.keys(cfg).forEach(k=>{var el=$(k);if(el&&cfg[k]!==undefined&&cfg[k]!==null){el.value=cfg[k]}})}).catch(()=>{})}"
"function scan(ev){var btn=ev&&ev.target?ev.target:event.target;btn.textContent='Scanning...';btn.disabled=true;fetch('/scan').then(r=>r.json()).then(list=>{var el=$('ap-list');el.style.display='block';el.innerHTML='';list.forEach(ap=>{var d=document.createElement('div');d.className='ap-item';d.innerHTML='<span>'+(ap.auth?'<span class=ap-lock></span>':'')+ap.ssid+'</span><span class=ap-rssi>'+ap.rssi+' dBm</span>';d.onclick=function(){$('ssid').value=ap.ssid};el.appendChild(d)});btn.textContent='Scan WiFi Networks';btn.disabled=false}).catch(()=>{btn.textContent='Scan WiFi Networks';btn.disabled=false})}"
"function saveConfig(){var fields=['ssid','password','api_key','model','provider','base_url','tg_token','feishu_app_id','feishu_app_secret','proxy_host','proxy_port','proxy_type','search_key','tavily_key','voice_stream_url','voice_codec'];var data={};fields.forEach(f=>{data[f]=$(f).value.trim()});$('save_status').style.display='block';fetch('/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(()=>{$('save_status').textContent='Saved! Restarting...'}).catch(()=>{$('save_status').textContent='Error. Please try again.'})}"
"loadConfig();refreshStatus();"
"</script>"
"</body></html>";
